### ISSUE TITLE
html上のボタンクリック→アラートダイアログの表示方法について

### ISSUE THREAD

**Issue by yokikoshimizu** [yokikoshimizu/react_yockey#1]
@SatakeYusuke19920527 
お疲れ様です！

表題の件について質問がございます。

前回の講義で作成途中だったwindow.alertのダイアログですが、
現在アプリをブラウザで起動した際にポップアップされるようになっています。
これを「Hello World」のボタンを押すことによって表示されるようにしたいのですが、
必要なコーディングは何でしょうか？
プッシュしたコードをご確認いただけますと幸いです！

以上、ご回答のほど、よろしくお願いいたします！

**Comment by SatakeYusuke19920527** [comment]
このサイトがオヌヌメです。
https://qiita.com/jima-r20/items/839da7c2f26366491298

**Comment by SatakeYusuke19920527** [comment]
これも終了できたら、Closeしておいてください！

**Comment by yokikoshimizu** [comment]
@SatakeYusuke19920527 
お疲れ様です！

解決しました！プッシュしておいたのでご確認ください！
ただ、今回書いたコードの原理を全て理解できたわけではないので、また受講時に質問させてください！

ありがとうございました！

**Comment by SatakeYusuke19920527** [comment]
ちゃんとできていますね！
最高です！
