### ISSUE TITLE
Cars.jsを使用した各プロパティ（id,name,date）のブラウザ出力

### ISSUE THREAD

**Issue by yokikoshimizu** [yokikoshimizu/react_yockey#2]
@SatakeYusuke19920527 
お疲れ様です。

標記の件、タイトル通りなのですが、

■id, name, date で定義してコードへ書いた各要素はブラウザへ反映される
■…が、上三つのプロパティも文字列として表記することがまだできていない

という状態です。
課題に「Card.jsを使って」と書いてあったので、Appの方ではなくCardの方のコーディングなのかなとは思っているのですが、
こちらの問題についてヒントをいただけますと幸いです！

よろしくお願いいたします！

**Comment by SatakeYusuke19920527** [comment]
以下、ご確認お願いします。

- コードを見せてください。
- ExtraはCard.jsを使用しなくて大丈夫ですよ！

**Comment by yokikoshimizu** [comment]
こちらの件につきましてはまた受講時に伺います！
