### ISSUE TITLE
ヘッダー部分の一括化につきまして

### ISSUE THREAD

**Issue by yokikoshimizu** [yokikoshimizu/react_yockey#3]
@SatakeYusuke19920527 
お世話になります。

さきほど新しく書いたコードをプッシュしました！
早速アドバイスをいただいたとおりにtableタグを使用しましたが、現在の問題点は表題の通りです。
id,name,dateがwrapperで作られた各箱において繰り返され、ヘッダー化できません。。。

（※ボーダーに色がついていますがこちらはヘッダー化ができ次第CSSで消そうと思っています）

こちらについて解決策がございましたらアドバイスいただけますと幸いです。

よろしくお願いいたします！

**Comment by SatakeYusuke19920527** [comment]
tableのheaderもmapでぐるぐる回しているからですね。
mapでぐるぐる回すのはbodyの部分だけで大丈夫ですよ！

**Comment by yokikoshimizu** [comment]
@SatakeYusuke19920527 
お疲れ様です。

今、最新のコードをプッシュしました。

＞tableのheaderもmapでぐるぐる回しているからですね。
mapでぐるぐる回すのはbodyの部分だけで大丈夫ですよ！

この意味は理解できたのですが、文章の意図通りにコードを書けませんでした。。。
Card.jsの方は使用しないとのことなので、Appの方でconstを使用したコンポーネントを const App の下へ
追加するのかなと予想して取り組みましたが、色々書いてみてうまくいきませんでした。。。

追加ヒントをいただけますと幸いです！
よろしくお願いいたします！

**Comment by SatakeYusuke19920527** [comment]
# mapを回す位置
今、Card.jsへ書いているtableタグを全てApp.jsへ持ってきましょう！
```
<table>
 <theader>
 </theader>
 <tbody>
 {...ここでmapを回す感じ}
 </tbody>
</table>
```

ここです！

**Comment by yokikoshimizu** [comment]
お疲れ様です！

アドバイスいただいたとおりにApp.jsを修正したところ、なんとかそれっぽくすることができました！
詳しくはプッシュした最新のコードをご覧ください！

ヘッダー部分とボティのインデントが揃っていないので、またそこについて受講時にお伺いできればと思います！
※display:flexを久々に使ってインデント問題に取り組みましたがどうやらそれでは駄目なような。。。

**Comment by SatakeYusuke19920527** [comment]
いい感じですね。
今回に関しては、インテンドはよしとします。
後々cssで綺麗にするので大丈夫ですよ！

**Comment by yokikoshimizu** [comment]
こちらクローズしますね！
