### ISSUE TITLE
「Can't resolve 'bootstrap/dist/css/bootstrap.min.css'」について

### ISSUE THREAD

**Issue by yokikoshimizu** [yokikoshimizu/react_yockey#6]
おつかれさまです！
遅くなってしまい申し訳ございません。たった今、何度か修正を試みたコードをプッシュしました。

./src/components/ComponentA.js
Module not found: Can't resolve 'bootstrap/dist/css/bootstrap.min.css' in 'C:\prj\react_yockey\src\components'

というエラーがどうしても消えず。。。
bootstrapのcssって「import 'bootstrap/dist/css/bootstrap.min.css';」の他に宣言させる必要のあるものはありましたか…？

ご回答、よろしくお願いいたします。

**Comment by SatakeYusuke19920527** [comment]
以下をgit bashからやっちゃってください！
```
npm install react-bootstrap bootstrap@5.1.3
```

**Comment by yokikoshimizu** [comment]
上記のエラーがなくなりました！ありがとうございます！
